# Generated by Django 5.2.7 on 2025-12-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='available_days',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='visiting_time',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='opticket',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(default='Waiting', max_length=50),
        ),
    ]
